<?php

declare(strict_types=1);

/**
 * Canonical command definitions shared by restart UI and proxy.
 */
function restartCommandDefinitions(): array {
    return [
        'restart' => [
            'method' => 'POST',
            'path' => '/api/restart',
            'label' => 'Restart',
            'description' => 'Restart the automation process.',
            'group' => 'process',
            'order' => 10,
            'confirmTitle' => 'Confirm Restart',
            'confirmBody' => 'This restarts the automation process immediately. Active control stops briefly during restart.',
            'confirmAction' => 'Restart',
            'buttonClass' => 'btn-process',
            'expect_disconnect' => true,
        ],
        'pause_on' => [
            'method' => 'POST',
            'path' => '/api/pause?state=on',
            'label' => 'Pause On',
            'description' => 'Force pause mode (desired power = 0).',
            'group' => 'automation',
            'order' => 10,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-warning',
            'expect_disconnect' => false,
        ],
        'pause_off' => [
            'method' => 'POST',
            'path' => '/api/pause?state=off',
            'label' => 'Pause Off',
            'description' => 'Resume schedule control (disable pause).',
            'group' => 'automation',
            'order' => 20,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-resume',
            'expect_disconnect' => false,
        ],
        'refresh_schedule' => [
            'method' => 'GET',
            'path' => '/api/refresh',
            'label' => 'Refresh Schedule',
            'description' => 'Force schedule refresh from API.',
            'group' => 'automation',
            'order' => 30,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-refresh',
            'expect_disconnect' => false,
        ],
        'slow_charge_0' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=0',
            'label' => '0 W',
            'description' => 'Set runtime slow-charge max power to 0 W.',
            'group' => 'slow_charge',
            'order' => 10,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-info',
            'expect_disconnect' => false,
        ],
        'slow_charge_100' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=100',
            'label' => '100 W',
            'description' => 'Set runtime slow-charge max power to 100 W.',
            'group' => 'slow_charge',
            'order' => 15,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-refresh',
            'expect_disconnect' => false,
        ],
        'slow_charge_240' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=240',
            'label' => '240 W',
            'description' => 'Set runtime slow-charge max power to 240 W.',
            'group' => 'slow_charge',
            'order' => 20,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-resume',
            'expect_disconnect' => false,
        ],
        'slow_charge_500' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=500',
            'label' => '500 W',
            'description' => 'Set runtime slow-charge max power to 500 W.',
            'group' => 'slow_charge',
            'order' => 30,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-warning',
            'expect_disconnect' => false,
        ],
        'slow_charge_800' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=800',
            'label' => '800 W',
            'description' => 'Set runtime slow-charge max power to 800 W.',
            'group' => 'slow_charge',
            'order' => 40,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-process',
            'expect_disconnect' => false,
        ],
        'slow_charge_1200' => [
            'method' => 'POST',
            'path' => '/api/slow_charge_max_power?value=1200',
            'label' => '1200 W',
            'description' => 'Set runtime slow-charge max power to 1200 W.',
            'group' => 'slow_charge',
            'order' => 50,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-danger',
            'expect_disconnect' => false,
        ],
        'log_debug' => [
            'method' => 'POST',
            'path' => '/api/loglevel?level=debug',
            'label' => 'Log Debug',
            'description' => 'Set runtime log level to DEBUG.',
            'group' => 'logging',
            'order' => 10,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-debug',
            'expect_disconnect' => false,
        ],
        'log_info' => [
            'method' => 'POST',
            'path' => '/api/loglevel?level=info',
            'label' => 'Log Info',
            'description' => 'Set runtime log level to INFO.',
            'group' => 'logging',
            'order' => 20,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-info',
            'expect_disconnect' => false,
        ],
        'log_warning' => [
            'method' => 'POST',
            'path' => '/api/loglevel?level=warning',
            'label' => 'Log Warning',
            'description' => 'Set runtime log level to WARNING.',
            'group' => 'logging',
            'order' => 30,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-warning',
            'expect_disconnect' => false,
        ],
        'log_error' => [
            'method' => 'POST',
            'path' => '/api/loglevel?level=error',
            'label' => 'Log Error',
            'description' => 'Set runtime log level to ERROR.',
            'group' => 'logging',
            'order' => 40,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-danger',
            'expect_disconnect' => false,
        ],
        'get_netzero_target_w' => [
            'method' => 'GET',
            'path' => '/api/netzero_target_w',
            'label' => 'Get Netzero Target',
            'description' => 'Get current runtime NETZERO_TARGET_W override.',
            'group' => 'netzero_target',
            'order' => 10,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-info',
            'expect_disconnect' => false,
            'ui' => false,
            'parameterized' => false,
        ],
        'set_netzero_target_w' => [
            'method' => 'POST',
            'path' => '/api/netzero_target_w',
            'label' => 'Set Netzero Target',
            'description' => 'Set runtime NETZERO_TARGET_W override as a signed integer.',
            'group' => 'netzero_target',
            'order' => 20,
            'confirmTitle' => '',
            'confirmBody' => '',
            'confirmAction' => '',
            'buttonClass' => 'btn-refresh',
            'expect_disconnect' => false,
            'ui' => false,
            'parameterized' => true,
        ],
    ];
}
